
    create table anime_list (
        created_date timestamp(6),
        id bigint generated by default as identity,
        release_date timestamp(6) not null,
        updated_date timestamp(6),
        created_by varchar(255),
        description varchar(255) not null,
        genre varchar(255) not null,
        name varchar(255) not null,
        studio varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

    create table anime_list (
        created_date timestamp(6),
        id bigint generated by default as identity,
        release_date timestamp(6) not null,
        updated_date timestamp(6),
        created_by varchar(255),
        description varchar(255) not null,
        genre varchar(255) not null,
        name varchar(255) not null,
        studio varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );
