CREATE TABLE anime_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   genre VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   studio VARCHAR(255) NOT NULL,
   release_date VARCHAR(255) NOT NULL,
   created_by VARCHAR(255),
   created_date TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   updated_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_animelist PRIMARY KEY (id)
);

ALTER TABLE anime_list ADD CONSTRAINT uc_animelist_name UNIQUE (name);

-- Inserir um anime_list
INSERT INTO anime_list (name, genre, description, studio, release_date)
VALUES ('Naruto', 'Ação, Aventura', 'A história segue Naruto Uzumaki, um jovem ninja com o sonho de se tornar o Hokage', 'Pierrot', '2002-10-03');

-- Inserir outro anime_list
INSERT INTO anime_list (name, genre, description, studio, release_date)
VALUES ('Death Note', 'Suspense, Sobrenatural', 'A série segue um estudante do ensino médio que encontra um caderno sobrenatural', 'Madhouse', '2006-10-04');

-- Inserir mais um anime_list
INSERT INTO anime_list (name, genre, description, studio, release_date)
VALUES ('Attack on Titan', 'Ação, Drama, Fantasia', 'A história se passa em um mundo onde a humanidade é ameaçada por gigantes', 'Wit Studio', '2013-04-06');

-- Inserir um quarto anime_list
INSERT INTO anime_list (name, genre, description, studio, release_date)
VALUES ('My Hero Academia', 'Ação, Superpoderes', 'A história se passa em um mundo onde as pessoas têm superpoderes', 'Bones', '2016-04-03');

-- Inserir um quinto anime_list
INSERT INTO anime_list (name, genre, description, studio, release_date)
VALUES ('One Piece', 'Aventura, Comédia', 'A série segue Monkey D. Luffy enquanto ele procura pelo One Piece', 'Toei Animation', '1999-10-20');


